name: DevSecOps Scan

on:
  push:
    branches: [ "main" ]

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Run Trivy Scanner for Files and Secrets
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs' # Проверяем файловую систему напрямую
        scan-ref: '.'    # Проверяем весь репозиторий и parser.py с ключом
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
